### ISSUE TITLE
Implement mobile-friendly mode

### ISSUE THREAD

**Issue by zelikos** [zelikos/zelikos.github.io#8]
As mentioned in #7, the site is largely broken on mobile devices.

**Comment by Akzel94** [comment]
1. It's fine (but not great) on Firefox Focus, sizes of various elements could be smaller there
2. Elements are way too big on Morph Browser on Ubuntu Touch
3. Elements are much smaller in Brave and Chrome

**Comment by Akzel94** [comment]
The site does look fine on desktop browsers, so I'm adjusting the scope of this issue to be more about implementing a mobile version/mobile-friendly mode for smaller screens.

**Comment by zelikos** [comment]
Closing as the current site design is a simple one-page link aggregate now
